=== ScreamingDev/phpsemver/etc/phpsemver.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Complex types -->
    <xs:complexType name="common_text" abstract="true">
        <xs:sequence>
            <xs:element name="br" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="trigger_type">
        <xs:sequence>
            <xs:element name="Classes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="IsAdded" minOccurs="0"/>
                        <xs:element name="IsRemoved" minOccurs="0"/>
                        <xs:element name="Methods" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="ReturnTypeChanged" minOccurs="0"/>
                                    <xs:element name="ReturnTypeRemoved" minOccurs="0"/>
                                    <xs:element name="IsAdded" minOccurs="0"/>
                                    <xs:element name="IsRemoved" minOccurs="0"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Namespaces" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="IsRemoved" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Functions" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="IsAdded" minOccurs="0"/>
                        <xs:element name="IsRemoved" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="description_type">
        <xs:simpleContent>
            <xs:extension base="common_text"/>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="ruleSet_type">
        <xs:sequence>
            <xs:element name="Description" type="description_type"/>
            <xs:element name="Trigger" type="trigger_type"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="phpsemver_type">
        <xs:sequence>
            <xs:element name="Description" type="description_type" maxOccurs="1"/>
            <xs:element name="RuleSet" type="ruleSet_type" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string"/>
    </xs:complexType>

    <!-- Root node -->
    <xs:element name="phpsemver" type="phpsemver_type"/>

</xs:schema>

=== ScreamingDev/phpsemver/lib/PHPSemVer/Rules/WordPress.xml
<?xml version="1.0"?>
<phpsemver
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/sourcerer-mike/phpsemver/support/3.x.x/etc/phpsemver.xsd"
        title="WordPress version semantics">

    <RuleSet name="feature">
        <Description>Increase second number with each new feature and reset the third.</Description>
        <Trigger>
            <Classes>
                <IsAdded />
                <Methods>
                    <IsAdded />
                    <BodyChanged />
                </Methods>
            </Classes>
            <Functions>
                <IsAdded />
            </Functions>
        </Trigger>
    </RuleSet>

    <RuleSet name="fix">
        <Description>Increase third number with each new fix.</Description>
        <Trigger>
            <Classes>
                <Methods>
                    <BodyChanged />
                </Methods>
            </Classes>
            <Functions>
                <BodyChanged />
            </Functions>
        </Trigger>
    </RuleSet>

</phpsemver>

=== ScreamingDev/phpsemver/lib/PHPSemVer/Rules/SemVer2.xml
<?xml version="1.0"?>
<phpsemver
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../etc/phpsemver.xsd"
        title="Semantic Versioning 2.0.0">
    <Description>
        Given a version number MAJOR.MINOR.PATCH, increment the:
        <br/>
        <br/>
        MAJOR version when you make incompatible API changes,
        <br/>
        MINOR version when you add functionality in a backwards-compatible manner, and
        <br/>
        PATCH version when you make backwards-compatible bug fixes.
        <br/>
        <br/>
        Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH
        format.
        <br/>
        The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",
        "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119.
    </Description>
    <RuleSet name="major">
        <Description>
            Major version X (X.y.z | X > 0) MUST be incremented
            if any backwards incompatible changes are introduced to the public API.
            It MAY include minor and patch level changes.
            Patch and minor version MUST be reset to 0 when major version is incremented.
        </Description>
        <Trigger>
            <Classes>
                <IsRemoved />
                <Methods>
                    <IsRemoved />
                </Methods>
            </Classes>
            <Functions>
                <IsRemoved />
            </Functions>
        </Trigger>
    </RuleSet>
    <RuleSet name="minor">
        <Description>
            Minor version Y (x.Y.z | x > 0) MUST be incremented if new,
            backwards compatible functionality is introduced to the public API.
            It MUST be incremented if any public API functionality is marked as deprecated.
            It MAY be incremented if substantial new functionality
            or improvements are introduced within the private code.
            It MAY include patch level changes.
            Patch version MUST be reset to 0 when minor version is incremented.
        </Description>
        <Trigger>
            <Classes>
                <IsAdded />
                <Methods>
                    <ReturnTypeChanged />
                    <IsAdded />
                </Methods>
            </Classes>
            <Functions>
                <IsAdded />
            </Functions>
        </Trigger>
    </RuleSet>
    <RuleSet name="patch">

    </RuleSet>
    <Filter>
        <Blacklist>
            <Pattern>@vendor/.*@</Pattern>
            <Pattern>@lib/Test/.*@</Pattern>
            <Pattern>@spec/.*@</Pattern>
        </Blacklist>
    </Filter>
</phpsemver>
